import { ScrollViewStyleReset } from 'expo-router/html';
import { type PropsWithChildren } from 'react';

// The web HTML shell for STATIC rendering. IMPORTANT: this app exports as an SPA (web.output: "single", see
// app.json), and Expo Router does NOT apply +html.tsx in that mode, the exported index.html gets Expo's
// default <head> with a bare <title> and none of the meta below. So for the live SPA the SEO / social meta is
// injected post-export by scripts/inject-web-meta.mjs (wired into deploy-web.yml + ci.yml); keep the two in
// sync. This file stays the head IF we ever switch to static rendering. The 1200x630 og:image
// (client/public/og.png) is generated by scripts/gen-og-image.mjs.

const TITLE = 'DoubleDone · a calmer kind of to-do';
const DESCRIPTION =
  'A calm, never-shame daily to-do app. It shows you only what today needs and quietly keeps everything you finish. Made for ADHD, autism, and OCD. Nothing is ever overdue.';
const URL = 'https://doubledone.app';
const IMAGE = `${URL}/og.png`;

export default function Root({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <title>{TITLE}</title>
        <meta name="description" content={DESCRIPTION} />
        <meta name="theme-color" content="#FAF6F1" />

        {/* Open Graph (iMessage, Slack, LinkedIn, Facebook, ...) */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content={URL} />
        <meta property="og:site_name" content="DoubleDone" />
        <meta property="og:title" content={TITLE} />
        <meta property="og:description" content={DESCRIPTION} />
        <meta property="og:image" content={IMAGE} />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:image:alt" content="DoubleDone · Today, finite and achievable" />

        {/* Twitter / X */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={TITLE} />
        <meta name="twitter:description" content={DESCRIPTION} />
        <meta name="twitter:image" content={IMAGE} />

        {/* Disable body scrolling on web so ScrollView components behave like native. */}
        <ScrollViewStyleReset />
      </head>
      <body>{children}</body>
    </html>
  );
}
