// German catalog. DRAFT, pending native review (Phase 4 of the German version). Mirrors
// en.ts key-for-key (the `: Catalog` type enforces that); translate() falls back to en per
// missing key at runtime. Produced 2026-08-08 by the 19-agent translation panel (nine
// native translators, nine judges, one terminology editor), briefed on the glossary at
// docs/design-source/german-glossary.md. Register: warm du, never Sie; warmth by modal
// particle, never exclamation mark; the shame particles are banned. Idioms are
// TRANSCREATED, not literal ("Feierabend machen", "Mach Schritte draus", "Kopf leeren").
// "DoubleDone" and "Settle" never translate. Hand-edits welcome (the reviewer pass lands here).
import { type Catalog } from './en';

export const de: Catalog = {
  actions: {
    breakItDown: 'Mach Schritte draus',
    chartACourse: 'Kurs setzen',
    lightenToday: 'Mach heute leichter',
    makeItTiny: 'Mach es winzig',
    planMyDay: 'Plan meinen Tag',
    sortForMe: 'Sortier für mich',
  },
  breakdown: {
    addCountTasksOne: '{count} Aufgabe hinzufügen',
    addCountTasksOther: '{count} Aufgaben hinzufügen',
    aiDisclosure: 'Deine Aufgabe wird an eine KI geschickt, die die Schritte vorschlägt, und anonym gespeichert (kein Name, kein Konto), um die Vorschläge zu verbessern.',
    answerA11y: 'Antwort auf die Frage',
    breakDown: 'Mach Schritte draus',
    intoSmallSteps: 'ganz kleine',
    breakDownTaskLabel: 'Aus {title} Schritte machen',
    defaultQuestion: {
      custom: 'Gibt es etwas daran, das die Schritte verändern würde?',
      dueDate: 'Bis wann willst du das fertig haben?',
      spread: 'Die Schritte über ein paar Tage verteilen, oder alles an einem Tag?',
    },
    editStepA11y: 'Schritt bearbeiten: {title}',
    laterPhasesHead: 'Dann, wenn du so weit bist',
    laterPhasesNote: 'Die warten in „Später“. Wenn du bei einer ankommst, mach Schritte draus.',
    manualHint: 'Kleinere Teile von „{title}“. Ein Schritt pro Zeile. Sie werden zu einer Checkliste darunter, und wenn alle fertig sind, ist die Aufgabe es auch.',
    manualInputA11y: 'Die Schritte, einer pro Zeile',
    manualPlaceholder: 'erster kleiner Schritt\nnächster kleiner Schritt',
    manualSubmitA11y: 'Aus der Aufgabe diese Schritte machen',
    manualTitle: 'Mach Schritte draus',
    optionalPlaceholder: 'Optional',
    pickADate: 'Wähl ein Datum',
    planError: 'Das hat gerade nicht geklappt. Deine Aufgabe ist noch da, magst du es noch mal versuchen?',
    planTitle: 'Hier ist der Plan',
    questionsTitle: 'Ein paar kurze Fragen',
    removeStepA11y: 'Schritt entfernen: {title}',
    spreadGradual: 'Nach und nach',
    spreadSameDay: 'An einem Tag',
    stepInputA11y: 'Text des Schritts',
    stepMeta: '{minutes} Min. · {date}',
    stepRowA11yOne: '{title}, {minutes} Minute, {date}',
    stepRowA11yOther: '{title}, {minutes} Minuten, {date}',
    stepTitleWithMinutes: '{title} ({minutes} Min.)',
    tapToKeepOrSkip: 'Tipp auf einen Schritt, um ihn zu behalten oder wegzulassen.',
    thisWeek: 'Diese Woche',
    twoWeeks: 'Zwei Wochen',
    waitNote: 'Ich überlege mir ein paar kleine Schritte. Das dauert einen Moment, du musst hier nicht warten.',
  },
  capture: {
    add: 'Hinzufügen',
    addA11y: 'Etwas hinzufügen, für heute oder einen anderen Tag',
    addN: '{count} hinzufügen',
    aiNote: '„Sortier für mich“ und „Mach Schritte draus“ schicken, was du tippst, an Claude von Anthropic.',
    aiNoteBoth: "Sortier das für mich, Aufteilen und Scannen senden, was du tippst oder fotografierst, an Anthropics Claude.",
    aiNoteScan: "Scannen sendet dein Foto an Anthropics Claude.",
    allowCamera: 'Kamera erlauben',
    allowCameraA11y: 'Die Kamera erlauben',
    breakDownA11y: 'Mit KI Schritte draus machen',
    breakDownError: 'Das hat gerade nicht geklappt. Noch mal versuchen?',
    breakingDown: 'Mache Schritte draus…',
    change: 'Ändern',
    chooseFromPhotos: 'Lieber aus den Fotos wählen',
    chooseFromPhotosA11y: 'Stattdessen aus deinen Fotos wählen',
    choosePhoto: 'Wähl ein Foto',
    choosePhotoA11y: 'Ein Foto deiner Liste wählen',
    choosePhotoHint: 'Wähl ein Foto von einer Liste, einem Zettel oder einem Whiteboard.',
    collapseA11y: 'Den Eingabebereich einklappen',
    dictationError: 'Ich konnte das nicht verstehen. Versuch es noch mal, oder tipp einfach.',
    doorA11y: 'Wann, Wiederholung und Schritte. Aktuell: {summary}',
    doorA11yComposed: '{rows}. Aktuell: {summary}',
    anytime: 'Irgendwann',
    doorOverline: 'Wann · Wiederholung · Schritte',
    errorNoTasksRead: 'Ich konnte darauf keine Aufgaben erkennen. Versuch es noch mal, mit der Liste groß im Bild.',
    errorOpenPhotos: 'Deine Fotos ließen sich nicht öffnen. Versuch es noch mal.',
    errorPrepareImage: 'Das Bild ließ sich nicht verarbeiten. Versuch es noch mal.',
    errorReadPhoto: 'Das Foto ließ sich gerade nicht lesen. Noch mal versuchen?',
    errorTakePhoto: 'Das Foto ließ sich nicht aufnehmen. Versuch es noch mal.',
    everyNDays: 'Alle {count} Tage',
    fewerDaysA11y: 'Weniger Tage',
    inputA11y: 'Kopf leeren. Eine oder mehrere Sachen hinzufügen, eine pro Zeile',
    listening: 'Ich höre zu…',
    modeDaily: 'Täglich',
    modeEveryN: 'Alle paar Tage',
    modeWeekly: 'Wöchentlich',
    moreDaysA11y: 'Mehr Tage',
    noSteps: 'Keine Schritte',
    photoEgressNote: 'Dein Foto wird an die KI geschickt, damit sie deine Liste lesen kann, und danach verworfen. Es wird nie gespeichert.',
    photosButton: 'Fotos',
    pickDate: 'Wähl ein Datum',
    pickerTitleDue: 'An welchem Tag',
    placeholder: 'Schreib dir den Kopf leer. Eine Zeile pro Sache.',
    readingYourList: 'Ich lese deine Liste…',
    repeatOnDayA11y: 'Am {day} wiederholen',
    rowRepeats: 'Wiederholung',
    rowSteps: 'Schritte',
    rowWhen: 'Wann',
    scan: 'Scannen',
    scanA11y: 'Ein Foto deiner Liste scannen',
    sortA11y: 'Mit KI sortieren',
    sortError: 'Sortieren hat gerade nicht geklappt. Versuch es noch mal.',
    sorting: 'Sortiere…',
    speak: 'Sprechen',
    speakA11y: 'Deine Aufgaben einsprechen, statt zu tippen',
    speakListeningA11y: 'Ich höre zu. Tipp, um zu stoppen.',
    splitError: 'Aufteilen hat gerade nicht geklappt. Versuch es noch mal, oder schreib jede Sache in eine eigene Zeile.',
    startingFrom: 'Ab',
    startingFromA11y: 'Ab dem {date}',
    stepsHintOff: 'Hat es Teile? Mach Schritte draus.',
    stepsHintOn: 'Tipp sie auf „Heute“ an, dann geht’s einen Schritt weiter.',
    stepsOneOff: 'Schritte sind für Aufgaben, die sich nicht wiederholen.',
    stepsOneThing: 'Schritte sind für eine Sache, nicht für mehrere.',
    takePhotoA11y: 'Ein Foto deiner Liste aufnehmen',
    tidy: 'Mach Aufgaben draus',
    tidyA11y: 'Mit KI Aufgaben draus machen',
    tidying: 'Mache Aufgaben draus…',
    weekdayShortFri: 'Fr',
    weekdayShortMon: 'Mo',
    weekdayShortSat: 'Sa',
    weekdayShortSun: 'So',
    weekdayShortThu: 'Do',
    weekdayShortTue: 'Di',
    weekdayShortWed: 'Mi',
    weeklyOn: 'Wöchentlich am {days}',
  },
  celebrate: {
    affirmations: {
      didntNeedPerfect: 'Fertig. Es musste nicht perfekt sein.',
      doneIsDone: 'Fertig ist fertig. Notiert.',
      filed: 'Abgelegt. Du darfst jetzt aufhören nachzusehen.',
      goodEnough: 'Gut genug ist fertig. Lass es los.',
      letItRest: 'Geschafft. Lass es ruhen.',
      offTheList: 'Runter von der Liste. Schön gemacht.',
      offYourPlate: 'Das ist vom Tisch.',
      oneThingLighter: 'Eine Sache leichter.',
    },
    bloomEyebrow: 'Du hast das Ganze geschafft',
    finish: {
      allDone: 'Alles geschafft.',
      stepsOne: '{count} kleiner Schritt.',
      stepsOther: '{count} kleine Schritte.',
    },
    linger: {
      days: '{count} Tage, seit du es zum ersten Mal aufgeschrieben hast.',
      months: '{count} Monate, seit du es zum ersten Mal aufgeschrieben hast.',
      oneDay: 'Ein Tag, seit du es zum ersten Mal aufgeschrieben hast.',
      oneMonth: 'Ein Monat, seit du es zum ersten Mal aufgeschrieben hast.',
      oneWeek: 'Eine Woche, seit du es zum ersten Mal aufgeschrieben hast.',
      weeks: '{count} Wochen, seit du es zum ersten Mal aufgeschrieben hast.',
    },
  },
  chart: {
    addTasksA11yOne: '{count} Aufgabe zu Heute hinzufügen',
    addTasksA11yOther: '{count} Aufgaben zu Heute hinzufügen',
    addTasksOne: '{count} Aufgabe hinzufügen',
    addTasksOther: '{count} Aufgaben hinzufügen',
    byWhen: 'Bis wann?',
    charting: 'Setze den Kurs…',
    chipInAMonth: 'In einem Monat',
    chipInThreeMonths: 'In 3 Monaten',
    chipInTwoMonths: 'In 2 Monaten',
    chipInTwoWeeks: 'In 2 Wochen',
    chipNoDeadline: 'Kein Zieldatum',
    egressNote: 'Dein Ziel geht an eine KI, die Schritte vorschlägt, und wird danach verworfen. Nichts wird hinzugefügt, bevor du dich entscheidest.',
    goalA11yLabel: 'Dein Ziel',
    goalPlaceholder: 'z. B. fit werden für einen 10-km-Lauf, drei einfache Gerichte kochen lernen',
    intro: 'Nenn etwas, worauf du hinarbeitest. Du bekommst eine ruhige Liste der nächsten Schritte, und du kannst sie nehmen oder lassen.',
    mapError: 'Ich konnte daraus gerade keinen Kurs machen. Magst du das Ziel anders formulieren?',
    pickAStep: 'Such dir einen Schritt aus',
    spreadNote: 'Der erste Schritt landet auf Heute, der Rest verteilt sich sanft {spreadHint}. Sie werden ganz normale Aufgaben.',
    spreadNoteOverNextDays: 'über die nächsten Tage',
    spreadNoteTowardDeadline: 'bis zu deinem Zieldatum',
    startOver: 'Nicht diese, nochmal von vorn',
    startOverA11y: 'Mit einem anderen Ziel von vorn beginnen',
    stepMinutes: '{minutes} Min.',
    suggestSteps: 'Schritte vorschlagen',
    suggestStepsA11y: 'Schritte zu diesem Ziel vorschlagen',
  },
  closeDay: {
    addDifferentDayLabel: 'Für einen anderen Tag hinzufügen',
    addForWhen: 'Für {when} hinzufügen',
    anythingElse: 'Hast du sonst noch etwas gemacht?',
    artAlt: 'Ein ruhiger Abendhimmel legt sich über ein zugeklapptes Notizbuch',
    bedtimeInputLabel: 'Etwas für morgen hinzufügen, eine Sache pro Zeile',
    bedtimePlaceholder: 'Eine Sache pro Zeile',
    bedtimePrompt: 'Geht dir etwas für morgen im Kopf herum? Schreib es hier auf und lass es los.',
    bedtimeSavedConfirm: 'Für {when} gespeichert. Ruh dich gut aus.',
    changeDay: 'Tag ändern',
    finishedPlainOne: 'Du hast heute {count} Sache geschafft.',
    finishedPlainOther: 'Du hast heute {count} Sachen geschafft.',
    finishedWithBigOne: 'Du hast heute {count} Sache geschafft, und die war viel.',
    finishedWithBigOther: 'Du hast heute {count} Sachen geschafft, eine davon war viel.',
    goodnight: 'Gute Nacht',
    notTomorrow: 'Nicht morgen?',
    noteA11y: 'Was du heute sonst noch gemacht hast',
    notePlaceholder: 'Was nicht auf der Liste stand…',
    pickDayTitle: 'Für welchen Tag hinzufügen',
    quietDay: 'Ein ruhiger Tag. Das darf sein.',
    reopen: 'Heute wieder öffnen',
    restedFinishedOne: 'Du hast heute {count} Sache geschafft. Ruh dich gut aus.',
    restedFinishedOther: 'Du hast heute {count} Sachen geschafft. Ruh dich gut aus.',
    restedQuiet: 'Ein ruhiger Tag, und das darf sein. Ruh dich gut aus.',
    restedSub: 'Morgen ist alles noch da.',
    waitingAheadA11y: 'Im Kalender ansehen, was geplant ist',
    waitingAheadOne: 'Eine Sache wartet auf die nächsten Tage. Sie ist gut aufgehoben.',
    waitingAheadOther: '{count} Sachen warten auf die nächsten Tage. Sie sind gut aufgehoben.',
    restedTitle: 'Du hast Feierabend gemacht.',
    rollForward: 'Was übrig ist, wandert auf morgen. Nichts geht verloren.',
    tomorrowInstead: 'Lieber morgen',
    tomorrowWord: 'morgen',
    windDown: 'Der Abend ist da. Mach Feierabend, wenn du so weit bist, auch ein bisschen zählt.',
    wrapTitle: 'Das war der Tag',
  },
  common: {
    back: 'Zurück',
    backToToday: 'Zurück zu Heute',
    begin: 'Beginnen',
    cancel: 'Abbrechen',
    close: 'Schließen',
    continue: 'Weiter',
    dismiss: 'Ausblenden',
    done: 'Fertig',
    goBack: 'Zurückgehen',
    gotIt: 'Alles klar',
    nextMonth: 'Nächster Monat',
    notNow: 'Jetzt nicht',
    off: 'Aus',
    offlineLine: 'Du scheinst offline zu sein. Dafür braucht es eine Verbindung, deine Aufgaben sind hier derweil gut aufgehoben.',
    on: 'An',
    premium: 'Premium',
    previousMonth: 'Vorheriger Monat',
    refresh: 'Aktualisieren',
    remove: 'Entfernen',
    send: 'Senden',
    skip: 'Überspringen',
    tick: '✓',
    today: 'Heute',
    tomorrow: 'Morgen',
    undo: 'Rückgängig',
  },
  estimate: {
    pace: {
      aboutADay: 'etwa ein Tag',
      aboutAWeek: 'etwa eine Woche',
      aboutNDays: 'etwa {days} Tage',
      coupleOfDays: 'ein paar Tage',
      line: 'Meist {span}, in ruhigem Tempo. Ganz ohne Eile.',
      weekOrTwo: 'eine Woche oder zwei',
    },
    weight: {
      clear: 'Ein freier Tag',
      clearLow: 'Ein freier Tag. Ruh dich aus.',
      full: 'Ein voller Tag, aber machbar.',
      heavy: 'Heute ist viel. Sei sanft mit dir.',
      light: 'Ein sanfter Tag. Luft zum Atmen.',
      lowFull: 'Ein Tag mit wenig Kraft. Sei sanft mit dir, der Rest kann warten.',
      lowHeavy: 'Ein Tag mit wenig Kraft, und heute ist viel. Such dir einfach eine Sache aus, der Rest wartet.',
      lowLight: 'Ein Tag mit wenig Kraft. Ein paar Sachen reichen völlig.',
    },
  },
  lookback: {
    aBigOne: 'eine, die viel war',
    dayCellA11y: '{date}, {count} geschafft{bigPart}{schedPart}',
    dayCellBig: ', eine davon war viel',
    dayCellSched: ', {sched} geplant',
    addForDay: 'Für diesen Tag eintragen',
    addForDayA11y: 'Etwas für {date} eintragen',
    addForDayPlaceholder: 'Eine Sache für diesen Tag',
    addedForDay: 'Für {date} eingetragen.',
    dayEmpty: 'An diesem Tag ist nichts notiert.',
    firstRunEmpty: 'Hier sammelt sich alles, was du schaffst. Noch ist nichts da, und genau so darf ein Anfang aussehen.',
    freeKeepsakeNote: 'Dein kostenloses Andenken für diesen Monat.',
    legendFinished: 'geschafft',
    legendScheduled: 'geplant',
    keepsakeSaved: 'Gespeichert. Teil es, wo immer du magst.',
    madeWithAi: 'Mit KI erstellt · {week}',
    shareKeepsake: 'Dieses Andenken teilen',
    shareKeepsakeA11y: 'Das Andenken-Bild dieser Woche teilen',
    shareUnavailable: 'Teilen ist hier nicht möglich.',
    makeScrapbook: 'Erinnerungsalbum machen',
    makeScrapbookA11y: 'Ein Erinnerungsalbum für die {week} machen',
    makingScrapbook: 'Dein Erinnerungsalbum entsteht…',
    monthEmpty: 'Bisher ein stiller Monat. Was du schaffst, erscheint hier.',
    patternsEmpty: 'Wenn du Dinge schaffst, sammeln sich deine Wochen und Monate hier.',
    patternsUpsell: 'Mit Premium siehst du, was deine Wochen und Monate zusammen ergeben.',
    patternsUpsellA11y: 'Mit Premium deine Muster sehen',
    reflectError: 'Der Blick auf deine Woche hat gerade nicht geklappt. Versuch es noch mal.',
    reflectOnWeek: 'Auf diese Woche zurückblicken',
    reflectOnWeekA11y: 'Mit KI auf diese Woche zurückblicken',
    reflectPrivacyNote: 'Was du diese Woche geschafft hast, geht an eine KI, die diesen Text schreibt, und wird danach gelöscht. Namen werden nicht gespeichert.',
    reflectingBusy: 'Ein Blick zurück auf deine Woche…',
    scheduledHeading: 'Geplant',
    scrapbookError: 'Das Erinnerungsalbum hat gerade nicht geklappt. Versuch es noch mal.',
    scrapbookHeading: 'Erinnerungsalbum',
    scrapbookImageA11y: 'Ein Erinnerungsalbum-Stillleben für die {week}: {caption}',
    scrapbookImageGone: 'Das Bild zu diesem Erinnerungsalbum gibt es nicht mehr. Magst du ein neues machen?',
    scrapbookInvite: 'Mach aus dieser Woche ein Erinnerungsalbum',
    scrapbookNeedsFinishes: 'Sobald du diese Woche ein paar Dinge geschafft hast, wartet ein Erinnerungsalbum auf dich.',
    scrapbookPrivacyNote: 'Was du diese Woche geschafft hast, geht an eine KI, die sich das Stillleben ausdenkt. Namen werden nicht gespeichert.',
    scrapbookWeeklyGateOne: 'Das war das Erinnerungsalbum für diese Woche. Das nächste ist in {days} Tag so weit.',
    scrapbookWeeklyGateOther: 'Das war das Erinnerungsalbum für diese Woche. Das nächste ist in {days} Tagen so weit.',
    statActiveDaysOne: 'Diesen Monat hast du an {count} Tag etwas geschafft.',
    statActiveDaysOther: 'Diesen Monat hast du an {count} Tagen etwas geschafft.',
    statBigWinsLike: ', zum Beispiel {title}',
    statBigWinsOne: 'Du hast dir {count} Sache zurückgeholt, die gewartet hatte{like}.',
    statBigWinsOther: 'Du hast dir {count} Sachen zurückgeholt, die gewartet hatten{like}.',
    statFinishedThisWeek: 'Diese Woche hast du {count} geschafft.',
    subtitle: 'Alles, was du wirklich geschafft hast, und die Tage, die noch kommen.',
    title: 'Kalender',
    weekListHeading: 'Diese Woche hast du geschafft',
  },
  ours: {
    addTo: 'Zu {name} hinzufügen',
    archive: 'Listen, die ihr geführt habt',
    bring: 'In mein Heute holen',
    bringBack: 'Zurückholen',
    bringSub: 'eine Kopie, auf deiner Liste',
    bringSubRepeat: 'nur die von heute, auf deiner Liste',
    broughtAlready: 'Schon in deinem Heute',
    changedSince: 'seit deinem letzten Blick geändert',
    codeBody: 'Dein Mensch tippt ihn auf dem eigenen Handy in DoubleDone ein und ist dabei mit der Adresse angemeldet, die du angegeben hast. Der Code funktioniert nur einmal und gilt einen Tag lang.',
    codeHint: 'Ein Code enthält nie 0, 1, I, L oder O.',
    codePlaceholder: 'K7M-P4Q',
    codeTitle: 'Lies ihn deinem Menschen vor',
    copied: 'Kopiert ✓',
    defaultName: 'Unsere Liste',
    deletePending: 'Bisher wurde niemandem etwas gesagt. Diese Liste wird gelöscht, sobald du diesen Bildschirm verlässt, und ein Tippen behält sie.',
    enterCode: 'Der Code von deinem Menschen',
    errAlreadyPaired: 'In DoubleDone gibt es erst mal immer nur eine gemeinsame Liste. Du kannst sie jederzeit verlassen, und es geht nichts verloren.',
    errBadEmail: 'Das sieht nicht nach einer E-Mail-Adresse aus.',
    errBadName: 'Hier braucht es einen Namen, damit dein Mensch dich ansprechen kann.',
    errInvalidCode: 'Mit dem Code hat es nicht geklappt. Ein Code gilt einen Tag lang und nur für die Adresse deines Kontos. Frag deinen Menschen ruhig nach einem neuen.',
    errListFull: 'Eine gemeinsame Liste ist für zwei Menschen, und diese Liste ist voll.',
    errNotOpen: 'Gemeinsame Listen sind noch nicht verfügbar. Wir haben nichts gespeichert.',
    errNotYours: 'Diese Liste ist geschlossen und lässt sich nicht mehr ändern.',
    errOffline: 'Gerade keine Verbindung. Versuch es gleich noch mal.',
    errOwnEmail: 'Das ist deine eigene Adresse.',
    errPartnerGone: 'Diese Liste bleibt zum Lesen hier, aufmachen lässt sie sich aber nicht mehr: dein Mensch ist nicht mehr dabei.',
    errRateLimited: 'Beitreten geht gerade nicht. Mit deinem Konto ist alles in Ordnung. In einer Stunde kannst du es ruhig noch mal versuchen.',
    errTooManyLists: 'Dieses Konto hat das Limit für gemeinsame Listen erreicht.',
    errUnknown: 'Das hat gerade nicht geklappt. Noch mal versuchen?',
    errUnpushed: 'Hier gespeichert, aber noch nicht auf der Liste deiner Person. Es versucht es weiter.',
    errClosedList: "Diese Liste ist geschlossen, Änderungen bleiben auf diesem Gerät.",
    forget: 'Diese Liste endgültig löschen',
    forgetHint: 'Das löscht die Liste mit allem, was darauf steht, und lässt sich nicht rückgängig machen. Hol dir vorher ruhig in dein Heute, was du behalten möchtest.',
    frozenBody: 'Es ist nichts verloren. Du kannst hier noch alles lesen und dir einzeln in dein Heute holen, was du magst.',
    frozenRow: 'Diese Liste ist geschlossen. Du kannst dir trotzdem eine Kopie nehmen.',
    frozenTitle: 'Diese Liste ist geschlossen',
    getCode: 'Code holen',
    handled: 'In unserer Liste erledigt. Es ist aus deinem Tag raus.',
    join: 'Beitreten',
    joinInstead: 'Mit einem Code beitreten',
    joined: 'Du teilst diese Liste jetzt mit {name}.',
    keepIt: 'Behalten',
    keptWith: 'Geteilt mit {name}',
    lead: "Eine Liste, die ihr beide führt. Was einen Tag hat, erscheint in beiden Heute. Alles andere bleibt hier.",
    leave: 'Diese Liste verlassen',
    leaveAloneHint: 'Es ist niemand dabei, also gibt es nichts zu schließen. Der Code funktioniert dann nicht mehr.',
    leaveHint: 'Es geht nichts verloren. Damit ist die Liste für euch beide geschlossen, lesen könnt ihr aber weiterhin alles.',
    listEmpty: 'Hier ist noch nichts. Was einer von euch einträgt, seht ihr beide.',
    namePlaceholder: 'Gib ihr einen Namen',
    newCode: 'Neuen Code holen',
    notThem: 'Doch nicht der richtige Mensch? Verlass die Liste.',
    openList: 'Liste öffnen',
    partnerJoined: '{name} ist dabei.',
    presetCare: 'Sich um jemanden kümmern',
    presetHouse: 'Der Haushalt',
    presetJustUs: 'Nur wir zwei',
    presetOwn: 'Selbst benennen',
    presetShop: 'Der Einkauf',
    putAway: 'Weglegen',
    recentlyRemoved: 'Kürzlich entfernt',
    recentlyRemovedHint: 'Was von der Liste genommen wird, wartet hier sieben Tage.',
    reopen: 'Gemeinsam wieder öffnen…',
    reopenHint: 'Das gibt dir einen Code für deine Person. Nichts öffnet sich, bis sie ihn benutzt.',
    repeat: 'Wiederholen…',
    repeatNote: 'Ihr seht sie beide an ihrem Tag.',
    repeatUnknown: 'In einem Rhythmus, den diese Version noch nicht lesen kann. Sie ist sicher, und nach einem Update erscheint sie wieder an ihren Tagen.',
    tickOnItsDay: "an ihrem Tag abhakbar",
    report: 'Diese Liste melden',
    reportHint: 'Das geht nur an uns. Deiner Person wird nichts gesagt, und auf ihrem Bildschirm ändert sich nichts.',
    reportedBody: 'Danke. Wir haben es und schauen es uns an. Deiner Person wurde nichts gesagt.',
    restore: 'Zurücklegen',
    restoreA11y: '{title} zurück auf die Liste legen',
    resumeCodeBody: 'Lies ihn deiner Person vor. Die Liste ist zurück, sobald sie ihn benutzt, genau so, wie ihr sie verlassen habt.',
    rowLabelOriginSuffix: ', aus eurer geteilten Liste',
    share: 'Code teilen',
    shareMessage: 'Eine gemeinsame Liste bei DoubleDone, falls du magst. Geh auf doubledone.app, melde dich mit der E-Mail-Adresse an, die ich für dich angegeben habe, tippe auf „Mit einem Code beitreten“ und gib {code} ein. Er gilt einen Tag lang.',
    shareTo: 'In unsere Liste teilen',
    todayHeading: 'Für heute · Unser',
    todayHeadingNamed: 'Für heute · {name}',
    sinceYouLooked: '{count} seit deinem letzten Blick',
    removeEndsRepeats: "Eine Wiederholung hier zu entfernen beendet sie für euch beide.",
    noLongerOn: "nicht mehr auf Unser",
    noLongerOnNamed: "nicht mehr auf {name}",
    takeOn: "Heute übernehmen",
    shareTrim: 'Auf Ours sind die Titel kürzer. Dieser wird passend gekürzt.',
    sharedToOurs: 'Zu eurer geteilten Liste hinzugefügt.',
    sharingWith: 'Geteilt mit {name}',
    showPutAway: 'Weggelegte anzeigen',
    signIn: 'Zum Teilen anmelden',
    signedOutBody: 'Ein Konto brauchen wir nur, um zu wissen, mit wem du teilst. Beim Anmelden landen auch deine eigenen Aufgaben in deinem Konto, wo nur du sie lesen kannst. Dein Mensch sieht sie nie, und an Heute ändert sich nichts.',
    signedOutTitle: 'Zum Teilen brauchst du ein Konto',
    start: 'Gemeinsame Liste anfangen',
    theirEmail: 'Die E-Mail-Adresse von deinem Menschen',
    theirEmailHint: 'Wir schicken nie eine E-Mail an diese Adresse. Der Code funktioniert nur für die Adresse, mit der dein Mensch bei DoubleDone angemeldet ist.',
    theirEmailPlaceholder: 'name@beispiel.de',
    waiting: 'Du kannst das ruhig schließen. Sobald dein Mensch dabei ist, siehst du den Namen. Ein Code gilt einen Tag lang, hol dir also einen neuen, wenn sich nichts tut.',
    wasntWho: 'Ich meinte jemand anderen',
    whatFor: 'Wofür ist diese Liste?',
    youAre: 'Sie sieht dich als {name}',
    yourName: 'Wie soll dich dein Mensch nennen?',
    yourNamePlaceholder: 'Dein Name',
  },
  phase: {
    greeting: {
      afternoon: 'Schönen Nachmittag. Nur heute.',
      evening: 'Der Tag klingt aus. Nur heute.',
      morning: 'Guten Morgen. Nur heute.',
    },
  },
  premium: {
    appleManageElsewhere: 'Dieses Abo wurde auf einem iPhone oder iPad gekauft, deshalb verwaltet Apple es. Öffne auf dem Gerät die Einstellungen, tippe auf deinen Namen und dann auf Abos.',
    applePerMonth: '{price} / Monat',
    applePerYear: '{price} / Jahr',
    appleRenewalTerms: 'Das Abo verlängert sich von selbst, bis du kündigst. Kündigen kannst du jederzeit in deinen Apple-ID-Einstellungen, bis einen Tag vor der Verlängerung.',
    appleStoreNote: 'Abgerechnet über deine Apple-ID.',
    billedViaStripe: 'Sichere Abrechnung über Stripe. Bedingungen und Erstattungen ›',
    brandName: 'DoubleDone Premium',
    iapUnavailable: 'Der App Store antwortet gerade nicht. Mit deinem Konto ist alles in Ordnung. Versuch es gleich noch mal.',
    privacyLink: 'Datenschutzerklärung',
    privacyLinkA11y: 'Datenschutzerklärung lesen',
    purchaseAlreadyOwned: 'Diese Apple-ID hat Premium schon. Tippe auf „Kauf wiederherstellen“, um es zurückzuholen.',
    purchaseCouldNotFinish: 'Das hat nicht geklappt. Es wurde nichts abgebucht.',
    purchaseNotAllowed: 'Käufe sind auf diesem Gerät ausgeschaltet, meist durch Bildschirmzeit oder eine Einschränkung.',
    purchasePending: 'Dein Kauf wartet auf eine Freigabe. Premium schaltet sich von selbst ein, sobald sie da ist, du musst nichts weiter tun.',
    purchaseStoreDown: 'Der App Store antwortet nicht. Es wurde nichts abgebucht. Versuch es später noch mal.',
    restoreFailed: 'Das ließ sich gerade nicht prüfen. Es hat sich nichts geändert. Versuch es gleich noch mal.',
    restoreNothingFound: 'Auf dieser Apple-ID gibt es nichts wiederherzustellen. Falls du woanders abonniert hast, melde dich mit diesem Konto an, dann folgt dir Premium hierher.',
    restorePurchases: 'Kauf wiederherstellen',
    restorePurchasesA11y: 'Einen früheren Premium-Kauf wiederherstellen',
    restoreRestored: 'Wiederhergestellt. Premium ist wieder an.',
    restoring: 'Wird geprüft…',
    termsLink: 'Nutzungsbedingungen',
    checkoutCancelled: 'Alles gut. Dein kostenloses monatliches Erinnerungsalbum ist immer da.',
    errorAlreadyPremium: 'Du bist schon Premium. Verwalten kannst du es über den Button oben.',
    errorBillingIssue: 'Eine Zahlung deines bestehenden Abos braucht kurz Aufmerksamkeit, es gibt also nichts Neues zu kaufen. Aktualisiere deine Karte, dann läuft Premium von selbst weiter.',
    errorCheckoutFailed: 'Die Kasse ließ sich nicht öffnen. Versuch es bitte noch mal.',
    errorCheckoutSignIn: 'Melde dich erst kurz an, damit Premium zu deinem Konto gehört.',
    errorPortalFailed: 'Das Abo-Portal ließ sich nicht öffnen. Versuch es bitte noch mal.',
    errorPortalSignIn: 'Bitte melde dich noch mal an.',
    errorTrialFailed: 'Der Gratismonat ließ sich gerade nicht starten. Versuch es noch mal.',
    errorTrialSignIn: 'Melde dich erst kurz an, damit der Gratismonat zu deinem Konto gehört.',
    featureChart: 'Kurs setzen, ein Ziel wird zu ruhigen nächsten Schritten',
    featureMore: 'und mehr ist unterwegs…',
    featurePatterns: 'Deine Muster, sanfte Statistiken und ein warmer Wochenrückblick',
    featurePin: 'Pinn dir die eine Sache des Tages an',
    featureEnergy: 'Energie-Abgleich ohne Limit, frag jederzeit, was gerade passt',
    featurePlanMyDay: 'Plan meinen Tag, eine sanfte Reihenfolge für heute',
    featureQuiet: 'Stille, ein randloser Look, in dem nichts schreit',
    featureScan: 'Scanne ein Foto deiner Liste direkt in Aufgaben',
    featureScrapbook: 'Ein wöchentliches KI-Erinnerungsalbum mit allem, was du geschafft hast',
    featureThemes: 'Sieben ruhige Farbthemen, damit es ganz deins wird',
    footAnonymousIap: 'Kein Konto nötig. Premium wohnt bei deiner Apple-ID, und wenn du dich irgendwann anmeldest, kommt es auch auf deine anderen Geräte. Schon Premium im Web? Melde dich zuerst an, dann weiß dieser Bildschirm Bescheid.',
    footSignedIn: 'Das kostenlose monatliche Erinnerungsalbum bleibt immer deins, auch ganz ohne Premium.',
    footSignedOut: 'Premium gehört zu deinem Konto und folgt dir so auf all deine Geräte. Das kostenlose monatliche Erinnerungsalbum bleibt immer deins.',
    freeScrapbookEvenIfCancel: 'Das kostenlose monatliche Erinnerungsalbum bleibt immer deins, auch wenn du kündigst.',
    goPremium: 'Hol dir Premium',
    goPremiumKeepIt: 'Hol dir Premium und behalt es',
    goPremiumKeepItA11y: 'Hol dir Premium, um es nach deinem Gratismonat zu behalten',
    headPremiumActive: 'Du bist Premium ✓',
    headTrialActive: 'Dein Gratismonat ✓',
    manageSubscription: 'Abo verwalten',
    manageSubscriptionA11y: 'Dein Abo verwalten oder kündigen',
    nothingToManage: 'Dein Premium geht auf uns, hier gibt es also nichts zu verwalten.',
    opening: 'Wird geöffnet…',
    openingCheckout: 'Kasse wird geöffnet…',
    paymentAttention: 'Dein Premium pausiert gerade, während eine Zahlung erneut versucht wird. Aktualisiere deine Karte, dann ist es wieder da. Du musst nichts neu kaufen.',
    paymentAttentionLink: 'Zahlungsdaten aktualisieren',
    paymentAttentionLinkA11y: 'Die Zahlungsdaten deines bestehenden Abos aktualisieren',
    planAnnual: 'Jährlich · 17 % sparen',
    planAnnualA11y: 'Jährlich, fünfzig Dollar im Jahr, etwa siebzehn Prozent gespart',
    planMonthly: 'Monatlich',
    planMonthlyA11y: 'Monatlich, fünf Dollar im Monat',
    premiumUntil: 'Premium bis {periodLabel}, danach wieder das kostenlose monatliche Erinnerungsalbum.',
    priceAnnual: 'A$50 / Jahr, rund zwei Monate geschenkt. Jederzeit kündbar.',
    priceMonthly: 'A$5 / Monat. Jederzeit kündbar. Keine Werbung, nie.',
    refreshA11y: 'Deinen Premium-Status aktualisieren',
    renews: 'Verlängert sich am {periodLabel}.',
    scrapbookGrows: 'Das wöchentliche Erinnerungsalbum wächst, je länger du bleibst:',
    settingUp: 'Danke. Dein Premium wird gerade eingerichtet, das hier aktualisiert sich gleich.',
    signInToGoPremium: 'Anmelden und Premium holen',
    stuckFoot: 'Auch nach einer Minute noch nichts? Schreib uns kurz über die Einstellungen, wir kümmern uns drum.',
    stuckNote: 'Das dauert gerade länger als sonst. Deine Zahlung ist angekommen, gib dem Ganzen eine Minute und tippe dann auf Aktualisieren.',
    subscribeAnnualA11y: 'Premium abonnieren, fünfzig Dollar im Jahr',
    subscribeMonthlyA11y: 'Premium abonnieren, fünf Dollar im Monat',
    termsLinkA11y: 'Nutzungsbedingungen und Erstattungsrichtlinie',
    tierFourAfterSixMonths: '4 nach sechs Monaten',
    tierOneAWeek: '1 pro Woche',
    tierTwoAfterTwoMonths: '2 nach zwei Monaten',
    trialAlreadyUsed: 'Deinen Gratismonat hattest du schon. Hol dir Premium, wann immer du magst, um alles zu behalten.',
    trialLink: 'Oder teste Premium einen Monat gratis',
    trialLinkA11y: 'Teste Premium einen Monat gratis, ganz ohne Karte',
    trialUntil: 'Gratis bis {periodLabel}, danach wieder das kostenlose monatliche Erinnerungsalbum. Es wird nie etwas abgebucht, außer du entscheidest dich, es zu behalten.',
    unlockedBodyFull: 'Alles ist freigeschaltet: Scannen, Anpinnen, Stille, die Farbthemen, Kurs setzen, Plan meinen Tag, Deine Muster, Energie-Abgleich ohne Limit und {allowance} wöchentliche Erinnerungsalben. Danke, dass du DoubleDone unabhängig hältst.',
    unlockedBodyGrowing: 'Alles ist freigeschaltet: Scannen, Anpinnen, Stille, die Farbthemen, Kurs setzen, Plan meinen Tag, Deine Muster, Energie-Abgleich ohne Limit und {allowance} wöchentliche Erinnerungsalben, und es werden mehr, je länger du bleibst. Danke, dass du DoubleDone unabhängig hältst.',
    unlockedBodyOneGrowing: 'Alles ist freigeschaltet: Scannen, Anpinnen, Stille, die Farbthemen, Kurs setzen, Plan meinen Tag, Deine Muster, Energie-Abgleich ohne Limit und {allowance} wöchentliches Erinnerungsalbum, und es werden mehr, je länger du bleibst. Danke, dass du DoubleDone unabhängig hältst.',
    upsellBody: 'Der ganze ruhige Tagesablauf bleibt kostenlos, für immer, mit der ganzen Entlastung und deinem Kalender. Premium, das sind die Extras, nie etwas, das du brauchst.',
    upsellHead: 'Mehr von dem, was du liebst.',
  },
  relative: {
    today: 'heute',
    tomorrow: 'morgen',
    yesterday: 'gestern',
  },
  reminders: {
    dailyBody: 'Dein Heute ist da, wenn du so weit bist.',
    dailyOn: 'Tägliche Erinnerung ist an',
    dailyTitle: 'DoubleDone',
    nudgeBody: 'Wann immer du so weit bist.',
    nudgeChannelName: 'Aufgaben-Stupser',
    nudgeHint: 'Später am Tag ein sanfter Stupser dazu, nie eine Deadline.',
    nudgeTitle: 'Erinnere mich…',
    nudgeTooLate: 'Für einen Stupser ist es heute ein bisschen spät. Morgen ist ja auch noch da.',
    offerText: 'Magst du einmal am Tag einen sanften Stupser zum Zurückkommen?',
    offerYes: 'Ja, erinnere mich',
    offerYesA11y: 'Ja, erinnere mich täglich',
    widgetOfferText: 'Magst du dein Heute auf dem Startbildschirm?',
    widgetOfferHow: 'Halte den Startbildschirm gedrückt, tippe auf Widgets und such dann DoubleDone.',
    widgetOfferYes: "Zeig mir, wie's geht",
    widgetOfferYesA11y: 'Zeig mir, wie ich das Startbildschirm-Widget hinzufüge',
    presetEvening: 'Heute Abend',
    presetOneHour: 'In 1 Stunde',
    presetThreeHours: 'In 3 Stunden',
    reason: {
      denied: 'Benachrichtigungen sind für DoubleDone aus. Schalte sie in deinen Einstellungen ein und versuch es dann noch mal.',
      error: 'Die Erinnerung ließ sich gerade nicht einrichten. Noch mal versuchen?',
      unsupported: 'Erinnerungen sind auf diesem Gerät nicht verfügbar.',
    },
    remindMe: 'Erinnere mich',
    remindMeA11y: 'Erinnere mich an diese Aufgabe',
    routineNudgeBody: 'Wenn du so weit bist. Ein Schritt reicht völlig.',
    toggleA11y: 'Tägliche Erinnerung ein- oder ausschalten',
    turnOn: 'Tägliche Erinnerung einschalten',
  },
  repeat: {
    closeDrawerA11y: 'Wiederkehrende Aufgaben schließen',
    editA11y: '{title} bearbeiten',
    editSheetTitle: 'Wiederkehrende Aufgabe bearbeiten',
    empty: 'Noch keine wiederkehrenden Aufgaben. Wenn du etwas hinzufügst, öffne Wann · Wiederholung · Schritte und wähl, wie es sich wiederholt.',
    everyDay: 'Jeden Tag',
    everyNDays: 'Alle {days} Tage',
    fromDate: '{base} · ab {date}',
    oneOff: 'Einmalig',
    removeSeriesA11y: '{title} und alle Wiederholungen entfernen',
    removed: 'Wiederkehrende Aufgabe entfernt.',
    skipTodayA11y: '{title} nur für heute entfernen',
    skipToday: 'Heute überspringen',
    skippedToday: 'Nur für heute übersprungen. Die Wiederholung läuft weiter.',
    subtitle: 'Deine täglichen und wiederkehrenden Aufgaben. Was heute dran ist, erscheint auch auf Heute.',
    notANotification: 'Eine wiederkehrende Aufgabe ERSCHEINT auf Heute, wenn ihr Tag kommt. Sie benachrichtigt dich nicht. Wenn du erinnert werden willst, halte die Aufgabe auf Heute gedrückt und wähl „Erinnere mich“, oder schalte die tägliche Erinnerung in den Einstellungen ein.',
    title: 'Wiederkehrend',
    titleInputA11y: 'Der Titel der Aufgabe',
    undoRemoveA11y: 'Das Entfernen der wiederkehrenden Aufgabe rückgängig machen',
  },
  rooms: {
    chartHint: 'Auf ein Ziel hin planen',
    closeMenuA11y: 'Menü schließen',
    lookbackHint: 'Alles, was du geschafft hast, und die Tage vor dir',
    oursHint: 'Eine Liste, die du mit einem anderen Menschen führst',
    premiumHintFreeAi: 'Andenken, mehr KI, deine Farbe',
    premiumHintFreeNoAi: 'Dein Farbthema und mehr',
    premiumHintSubscribed: 'Dein Abo verwalten',
    repeatingHint: 'Aufgaben, die wiederkommen',
    routinesHint: 'Sanfte Rituale, keine Streaks',
    settingsHint: 'Komfort, Zugriff, deine Daten',
  },
  routines: {
    add: 'Routine hinzufügen',
    edit: 'Bearbeiten',
    editA11y: '{name} bearbeiten',
    empty: 'Noch keine Routinen. Eine Routine ist eine Handvoll kleiner Schritte, die du am Stück machst, etwa ein Start in den Morgen oder ein Ausklang am Abend. Hak sie nach und nach ab. Morgen fangen sie frisch an, ohne Streak, den du halten musst.',
    nameA11y: 'Name der Routine',
    nameFirstHint: 'Gib ihr erst mal einen Namen, irgendwas reicht schon.',
    namePlaceholder: 'Name, zum Beispiel Morgen',
    new: '+ Neue Routine',
    nudgeAt: 'Stupser gegen {time}',
    nudgeAtA11y: 'Stupser für {name} um {time}',
    nudgeHint: 'Eine Erinnerung am Tag für diese Routine, nur wenn du magst.',
    nudgeTitle: 'Ein sanfter Stupser',
    progress: '{done} von {total}',
    removeA11y: '{name} entfernen',
    removed: 'Routine entfernt.',
    rhythmActiveHours: 'Aktive Stunden',
    rhythmAddMeds: 'Medikamente, um 8 und um 20 Uhr',
    rhythmAddStand: 'Aufstehen, stündlich',
    rhythmAddTime: '+ Zeit hinzufügen',
    rhythmAddWater: 'Wasser, etwa alle 2 Stunden',
    rhythmAtTimes: 'Um {times}',
    rhythmEvery: 'Etwa alle {hours} Stunden, {start} bis {end}',
    rhythmEveryMinutes: 'alle {minutes} Minuten',
    rhythmEveryMinutesLine: 'Etwa alle {minutes} Minuten, {start} bis {end}',
    rhythmEveryMixed: 'alle {hours} Std. {minutes} Min.',
    rhythmEveryMixedLine: 'Etwa alle {hours} Std. {minutes} Min., {start} bis {end}',
    rhythmEveryN: 'alle {hours} Stunden',
    rhythmEveryOne: 'jede Stunde',
    rhythmHourly: 'Etwa jede Stunde, {start} bis {end}',
    rhythmHowOften: 'Wie oft',
    rhythmModeInterval: 'Immer mal wieder',
    rhythmModeTimes: 'Zu festen Zeiten',
    rhythmNameMeds: 'Medikamente',
    rhythmIntro: 'Sanfte Stupser im Rhythmus. Sie tippen dich an und sind wieder weg, nie eine Aufgabe, nie ein Streak.',
    rhythmLessOftenA11y: 'Seltener',
    rhythmMoreOftenA11y: 'Öfter',
    rhythmNamePlaceholder: 'Name, zum Beispiel Wasser oder Dehnen',
    rhythmNameStand: 'Aufstehen',
    rhythmNameWater: 'Wasser',
    batteryHint: 'Kommen Stupser zu spät an, oder gar nicht? Lass DoubleDone in den Systemeinstellungen ohne Akku-Einschränkungen laufen.',
    batteryOpen: 'App-Einstellungen öffnen',
    exactHint: 'Damit Stupser pünktlich ankommen, erlaube „Wecker & Erinnerungen“ für DoubleDone.',
    exactOpen: 'Wecker & Erinnerungen erlauben',
    nudgeHealthNext: 'Nächster Stupser gegen {time}.',
    nudgeHealthNone: 'Auf diesem Handy sind noch keine Stupser geplant. Speicher mal einen Rhythmus neu.',
    rhythmChannelLabel: 'Rhythmen',
    rhythmNew: '+ Neuer Rhythmus',
    rhythmRemoveTimeA11y: 'Diese Zeit entfernen',
    rhythmTimesHint: 'Füg mindestens eine Zeit hinzu.',
    rhythmTimesTitle: 'Zu diesen Zeiten',
    rhythmPause: 'Pausieren',
    rhythmPauseA11y: '{name} pausieren',
    rhythmPaused: 'Pausiert',
    rhythmResume: 'Fortsetzen',
    rhythmResumeA11y: '{name} fortsetzen',
    rhythmSave: 'Rhythmus hinzufügen',
    rhythmSection: 'Rhythmen',
    rhythmTo: 'bis',
    rhythmWebNote: 'Rhythmus-Erinnerungen kommen auf deinem Handy an.',
    saveChanges: 'Änderungen speichern',
    starter: 'Probier eine Morgenroutine',
    starterA11y: 'Eine Morgenroutine ausprobieren, vorausgefüllt und anpassbar',
    starterStepMedication: 'Medikamente nehmen',
    starterStepMovement: 'Ein paar Minuten Bewegung',
    starterStepOneThing: 'Die eine Sache für heute aufschreiben',
    starterStepWater: 'Ein Glas Wasser trinken',
    stepsA11y: 'Schritte der Routine, einer pro Zeile',
    stepsFirstHint: 'Füg mindestens einen Schritt hinzu, eine Zeile reicht völlig.',
    stepsPlaceholder: 'Schritte, einer pro Zeile',
    subtitle: 'Sanfte Rituale. Keine Streaks, kein Druck, nur heute.',
    timeEntry24hHint: 'Gib die Zeit im 24-Stunden-Format ein (20 = 8 Uhr abends).',
    timeEntryA11y: 'Zeit für den Stupser einstellen',
    timeHourA11y: 'Stunde',
    timeMinuteA11y: 'Minuten',
    title: 'Routinen',
    undoRemoveA11y: 'Das Entfernen der Routine rückgängig machen',
    whenAnytime: 'Jederzeit',
    whenEvening: 'Abends',
    whenMorning: 'Morgens',
  },
  scrapbook: {
    weekOf: 'Woche vom {date}',
  },
  settings: {
    accountLabel: 'Konto',
    aiConsentBody: 'Wenn du KI einschaltest, geht der Text, den du wählst, an Claude von Anthropic: eine Aufgabe, aus der Schritte werden sollen, ein Tag, der sortiert werden will. Alles andere bleibt immer auf deinem Gerät.',
    aiConsentTurnOn: 'KI einschalten',
    aiOffNote: 'KI ist aus. Alles bleibt auf deinem Gerät.',
    aiStatusOff: 'Aus. DoubleDone funktioniert komplett ohne KI, ganz auf deinem Gerät. Absichtlich so gebaut.',
    aiStatusOn: 'An. Schritte draus machen, Sortier für mich und das Erinnerungsalbum nutzen KI und schicken dafür den Text, den du wählst, an Claude.',
    appearanceHintFree: 'Eine Premium-Option: reduziert die Oberfläche auf ruhigen Text.',
    appearanceHintPremium: 'Stille reduziert die Oberfläche auf ruhigen Text. Standard behält die Karten und Buttons.',
    appearanceLabel: 'Oberfläche',
    appearanceQuiet: 'Stille',
    appearanceStandard: 'Standard',
    bandAccessData: 'Zugriff & Daten',
    bandAi: 'KI',
    bandComfort: 'Komfort',
    bandDeveloper: 'Entwickler',
    colourThemeHintFree: 'Sieben ruhige Paletten. Dämmerung ist immer kostenlos. Premium schaltet die anderen frei.',
    colourThemeHintPremium: 'Eine ruhige Palette für die ganze App. Dämmerung ist der Standard.',
    colourThemeLabel: 'Farbthema',
    confirmDeleteA11y: 'Kontolöschung bestätigen',
    copyMcpTokenA11y: 'Meinen MCP-Token kopieren',
    copyMyToken: 'Meinen Token kopieren',
    deleteAccountLink: 'Konto und Daten löschen',
    deleteAction: 'Löschen',
    deleteConfirmBody: 'Das löscht dein Konto und alles, was damit synchronisiert ist, endgültig. Das lässt sich nicht rückgängig machen.',
    deleteError: 'Löschen hat gerade nicht geklappt. Versuch es bitte noch mal.',
    deleting: 'Wird gelöscht…',
    devOverrideAuto: 'Auto',
    devOverrideFree: 'Free',
    devPremiumOverrideHint: 'Nur für lokales Testen. Erzwingt den Premium- oder Free-Zustand ohne echtes Abo. Landet nie in Produktion.',
    devPremiumOverrideLabel: 'Premium-Override',
    exportAction: 'Deine Daten exportieren',
    exportDone: 'Heruntergeladen. Gehört ganz dir.',
    exportError: 'Der Export hat gerade nicht geklappt. Noch mal versuchen?',
    exportHint: 'Deine Aufgaben und alles, was du geschafft hast, als Datei für dich. Ganz ohne Konto.',
    exporting: 'Wird exportiert…',
    feedbackCancelA11y: 'Feedback abbrechen',
    feedbackError: 'Senden hat gerade nicht geklappt. Versuch es bitte noch mal.',
    feedbackInputA11y: 'Dein Feedback',
    feedbackPlaceholder: 'Was funktioniert, was nicht, was du dir wünschst…',
    feedbackSending: 'Wird gesendet…',
    feedbackThanks: 'Danke. Es ist unterwegs.',
    footnote: 'Auf diesem Gerät gespeichert. Nichts davon verlässt es.',
    keepMyAccount: 'Mein Konto behalten',
    mcpDisconnect: 'KI-Konnektoren trennen',
    mcpDisconnectA11y: 'Alle KI-Konnektoren von diesem Konto trennen',
    mcpDisconnectDone: 'Getrennt. Verbundene Agenten müssen sich neu anmelden.',
    mcpDisconnectError: 'Trennen hat gerade nicht geklappt. Gleich noch mal versuchen?',
    mcpExpired: 'Deine Sitzung ist abgelaufen. Melde dich neu an, dann bekommst du einen frischen Token.',
    mcpExpiredA11y: 'Neu anmelden, um einen frischen Token zu bekommen',
    mcpFootnote: 'Der Token erneuert sich etwa stündlich. Kopier ihn neu, wenn dein Agent sich nicht mehr verbinden kann.',
    mcpHint: 'Lass einen KI-Agenten deine Aufgaben anlegen und abhaken. Trag diesen Server in deinem MCP-Client ein, dann füge deinen Token ein.',
    mcpLabel: 'Zugang für KI-Agenten (MCP)',
    motionFollowSystem: 'Wie das System',
    motionHint: 'Reduzieren stoppt die sanften Übergänge, die wandernden Titel und das leichte Vibrieren.',
    motionLabel: 'Bewegung',
    motionReduce: 'Reduzieren',
    premiumCardActiveA11y: 'DoubleDone Premium, aktiv',
    premiumCardActiveCue: 'Aktiv ✓',
    premiumCardActiveSub: 'Aktiv. Alle Extras gehören dir.',
    premiumCardSeePlansA11y: 'DoubleDone Premium, Tarife ansehen',
    premiumCardSubAi: 'Mehr von dem, was du liebst: Liste scannen, Kurs setzen, wöchentliche Erinnerungsalben und mehr.',
    premiumCardSubNoAi: 'Mehr von dem, was du liebst: dein Farbthema und mehr.',
    privacyLink: 'Privatsphäre & Daten ›',
    privacyLinkA11y: 'Privatsphäre und Daten',
    remindMeAt: 'Erinnere mich um',
    reminderAtA11y: 'Tägliche Erinnerung um {time}',
    reminderEarlier: 'Früher',
    reminderHint: 'Ein sanfter Stupser am Tag, der dich zurück zu deinem Tag holt. Mehr nicht.',
    reminderLabel: 'Tägliche Erinnerung',
    seeWelcomeAgain: 'Die Begrüßung noch mal ansehen',
    sendFeedback: 'Feedback senden',
    subtitle: 'Mach es dir gemütlich. Diese Einstellungen begleiten dich durch die ganze App.',
    swatchA11y: '{presetName}, ausgewählt, Premium',
    swatchPremiumSuffix: ', Premium',
    swatchSelectedSuffix: ', ausgewählt',
    syncedTo: 'Synchronisiert mit {email}',
    termsLink: 'AGB ›',
    termsLinkA11y: 'Nutzungsbedingungen',
    textSizeDefault: 'Standard',
    textSizeLabel: 'Textgröße',
    textSizeLarge: 'Groß',
    textSizeSmall: 'Klein',
    themeDark: 'Dunkel',
    themeHint: 'Dunkel richtet sich nach deinem Gerät, solange du nichts wählst.',
    themeLabel: 'Design',
    themeLight: 'Hell',
    themeSystem: 'System',
    title: 'Einstellungen',
    tokenCopied: 'Token kopiert ✓',
    turnAiOffA11y: 'KI ausschalten',
    turnAiOffLink: 'KI ausschalten ›',
    turnAiOnA11y: 'KI einschalten',
    turnAiOnLink: 'KI einschalten ›',
    yourDataLabel: 'Deine Daten',
  },
  settle: {
    aff1: 'du musst dir Ruhe nicht erst verdienen.',
    aff2: 'hier wird nichts gemessen.',
    aff3: 'die Liste läuft nicht weg.',
    aff4: 'so lange darf es dauern.',
    aff5: 'gerade braucht dich nichts.',
    aff6: 'du kannst hier nichts falsch machen.',
    aff7: 'du darfst bleiben, solange du magst.',
    guideIn: 'ein, ganz sanft…',
    guideOut: 'langsam aus…',
    guidePillOff: 'Atembegleitung · aus',
    guidePillOffA11y: 'Die Atembegleitung ist aus. Tippe, um sie einzuschalten.',
    guidePillOn: 'Atembegleitung · an',
    guidePillOnA11y: 'Die Atembegleitung ist an. Tippe, um sie auszuschalten.',
    guideRest: 'hier verweilen',
    leave: 'Gehen',
    leaveA11y: 'Den Raum verlassen und zu Heute zurückkehren',
    leavingLine: 'Heute ist noch da, wo du es gelassen hast.',
  },
  signIn: {
    codeA11y: 'Code aus deiner E-Mail',
    codeInvalid: 'Der Code hat nicht geklappt. Schau mal nach oder lass dir einen neuen schicken.',
    codePlaceholder: '6-stelliger Code',
    emailA11y: 'E-Mail-Adresse',
    emailMeACode: 'Schick mir einen Code',
    emailPlaceholder: 'du@beispiel.de',
    rateLimited: 'Gerade einen geschickt. Lass ihm eine Minute Zeit, dann versuch es noch mal.',
    resendCode: 'Code noch mal schicken',
    resendCooldownA11yOne: 'Code in {cooldown} Sekunde noch mal schicken',
    resendCooldownA11yOther: 'Code in {cooldown} Sekunden noch mal schicken',
    resendIn: 'Noch mal in {cooldown}s',
    sendFailed: 'Wir konnten den Code nicht schicken. Schau mal, ob die Adresse stimmt, und versuch es noch mal.',
    sentTo: 'Wir haben einen Code an {email} geschickt.',
    signIn: 'Anmelden',
    signOut: 'Abmelden',
    signedIn: 'Angemeldet',
    subtitle: 'Optional. Deine Aufgaben bleiben auf diesem Gerät, bis du dich anmeldest. Wir schicken dir einen 6-stelligen Code per E-Mail, du musst dir kein Passwort merken.',
    syncAcrossDevices: 'Auf allen Geräten synchronisieren',
    syncUnavailable: 'Synchronisieren geht hier nicht. Deine Aufgaben sind auf diesem Gerät sicher.',
    syncedAs: 'Deine Aufgaben werden jetzt mit {email} synchronisiert. Wir bringen dich zurück zu Heute.',
    useDifferentEmail: 'Andere E-Mail nehmen',
  },
  themes: {
    dusk: 'Dämmerung',
    fog: 'Nebel',
    heather: 'Heide',
    honey: 'Honig',
    rose: 'Rose',
    sage: 'Salbei',
    slate: 'Schiefer',
  },
  today: {
    addToToday: '+  Hinzufügen zu…',
    allDoneNote: 'Das war die Liste. Schön gemacht.',
    alsoDidA11y: 'Etwas festhalten, das du auch gemacht hast',
    alsoDidThat: '+ Hab ich auch gemacht',
    backToOneTaskAffirm: 'Wieder eine ganze Aufgabe.',
    bigTag: 'viel',
    cancelSelectionA11y: 'Auswahl abbrechen',
    changeStepsA11y: 'Die Schritte dieser Aufgabe ändern',
    closeTheDay: 'Feierabend machen',
    combine: 'Zusammenlegen',
    combineA11y: 'Ausgewählte Aufgaben zu einer zusammenlegen',
    combineConfirmA11y: 'Zu einer Aufgabe zusammenlegen',
    combineFindingName: 'Suche einen Namen…',
    combineHint: '{count} Aufgaben werden eine. Ändere den Namen oder behalte den Vorschlag. Sie landet auf dem frühesten ihrer Termine.',
    combineInputA11y: 'Der Name der zusammengelegten Aufgabe',
    combineModalTitle: 'Zu einer zusammenlegen',
    combinePlaceholder: 'Gib der neuen Aufgabe einen Namen…',
    combinedAffirm: 'Zusammengelegt zu einer: {title}.',
    didAdd: 'Eintragen',
    didHint: 'Etwas, das du geschafft hast und das nie auf der Liste stand. Es zählt trotzdem.',
    didInputA11y: 'Was hast du gemacht',
    didPlaceholder: 'Angerufen, spazieren gegangen…',
    didTitle: 'Was hast du gemacht?',
    doneOn: 'Erledigt am…',
    doneOnA11y: '{title} an einem früheren Tag als erledigt markieren',
    editTitleA11y: 'Titel bearbeiten: {title}',
    editTitleInputA11y: 'Der Titel der Aufgabe',
    doneOnAffirm: 'Für {day} festgehalten. Dein Kalender erzählt es so, wie es war.',
    doneOnTitle: "An welchem Tag hast du's gemacht?",
    easedOffAffirm: 'Wieder leichter. Nicht mehr markiert.',
    emptyArtAlt: 'Ein warmer Kaffee neben einem offenen Notizbuch im Morgenlicht',
    emptyNote: 'Noch nichts hier. Füg eine Sache hinzu oder genieß die Stille.',
    fewerStepsA11y: 'Weniger Schritte',
    focusAllDone: 'Das war fürs Erste alles.',
    focusChooseAnother: 'Eine andere wählen',
    focusDoneA11y: 'Fertig mit {title}',
    focusEmptyNote: 'Nichts mehr da für den Fokus. Ruh dich aus oder füg etwas hinzu, wenn du so weit bist.',
    focusExit: 'Verlassen',
    focusExitA11y: 'Fokus verlassen',
    focusLabel: 'Nur diese eine',
    focusOnTaskA11y: 'Fokus auf {title}',
    energyEntry: 'Was passt gerade?',
    energyEntryA11y: 'Fragen, was gerade zu deiner Energie passt',
    energyError: 'Gerade ließ sich nichts auswählen. Versuch es gleich noch mal.',
    energyGood: 'Gut drauf',
    energyLeft: 'Noch {count} deiner 15 kostenlosen Vorschläge diesen Monat.',
    energyLow: 'Fast leer',
    energyMedium: 'Irgendwo dazwischen',
    energyNotNow: 'Nicht jetzt',
    energyPrivacy: 'Deine offenen Aufgaben gehen an Claude, der eine auswählt. Nichts wird hinzugefügt oder geändert.',
    energyStart: 'Damit anfangen',
    energyThinking: 'Suche etwas Passendes…',
    energyTitle: 'Wie viel geht gerade?',
    focusOne: 'Nur eine Sache',
    focusStepOf: 'Schritt {step} von {total}',
    focusWhichOne: 'Welche?',
    gentleOrderAffirm: 'Eine sanfte Reihenfolge, oben auf der Liste, wenn du so weit bist.',
    holdHint: 'Halte eine Aufgabe gedrückt für mehr Möglichkeiten: Schritte draus machen, winzig machen, verschieben oder als viel markieren.',
    holdHintDismissA11y: 'Alles klar, diesen Tipp ausblenden',
    holdHintNoAi: 'Halte eine Aufgabe gedrückt für mehr Möglichkeiten: Schritte draus machen, verschieben oder als viel markieren.',
    holdToAdjust: 'Halten zum Anpassen',
    inDays: 'In {days} Tagen',
    laterHeading: 'Später',
    lightening: 'Wird leichter…',
    lowDayAffirm: 'Ein leiser Tag. Sei sanft mit dir, ein bisschen ist genug.',
    makeTinyLabel: 'Mach {title} winzig',
    makeWhole: 'Wieder ganz machen',
    makeWholeA11y: 'Diese wieder zu einer ganzen Aufgabe machen',
    markAsALot: 'Das ist viel',
    scrapbookOffer: 'Du hast diese Woche genug geschafft, um ein Andenken daraus zu machen. Es wartet in deinem Kalender.',
    scrapbookOfferGo: 'Zu deinem Kalender',
    tinyHint: 'der erste Schritt',
    toolSettle: 'Settle',
    weightHint: 'Gewicht',
    pinHint: 'bleibt ganz oben',
    pinnedTick: 'Angepinnt ✓',
    stepsCountHint: 'in Schritten zählen',
    stepsOf: '{done} von {total}',
    more: 'Mehr',
    moreExpandA11y: 'Mehr Aktionen',
    moreCollapseA11y: 'Weniger Aktionen',
    heldDoneIsDone: 'Erledigt ist erledigt.',
    markBigA11y: 'Die ausgewählten Aufgaben als viel markieren',
    markBigOneA11y: 'Diese Aufgabe als viel markieren',
    markSelectedDoneA11y: 'Ausgewählte als erledigt markieren',
    markedBigAffirm: 'Als viel markiert. Der Tag weiß jetzt, dass er mehr trägt.',
    menu: 'Menü',
    menuA11y: 'Menü: Wiederkehrend, Routinen, Kalender, Kurs setzen, Premium, Einstellungen',
    menuNoAiA11y: 'Menü: Wiederkehrend, Routinen, Kalender, Premium, Einstellungen',
    moreStepsA11y: 'Mehr Schritte',
    moveDown: '↓ Nach unten',
    moveDownA11y: '{title} in der heutigen Reihenfolge einen Platz nach unten schieben; die Karte bleibt offen',
    moveDownUnavailA11y: 'Nach unten nicht möglich, bereits ganz unten',
    movedDownAnnounce: 'Nach unten geschoben, {pos} von {total}.',
    movedUpAnnounce: 'Nach oben geschoben, {pos} von {total}.',
    moveSelectedA11y: 'Ausgewählte auf ein Datum verschieben',
    moveTo: 'Verschieben auf…',
    moveUp: '↑ Nach oben',
    moveUpA11y: '{title} in der heutigen Reihenfolge einen Platz nach oben schieben; die Karte bleibt offen',
    moveUpUnavailA11y: 'Nach oben nicht möglich, bereits ganz oben',
    noStepsYet: 'noch keine Schritte',
    moveToHintOne: 'Eine Aufgabe wandert auf den Tag, den du wählst.',
    moveToHintOther: '{count} Aufgaben wandern auf den Tag, den du wählst.',
    nextWeek: 'Nächste Woche',
    notALot: 'Doch nicht viel',
    offerDeferLine: 'Heute ist sortiert. Magst du ein paar Aufgaben auf spätere Tage schieben, damit es leichter wird?',
    offerDeferNo: 'Nein, so passt es',
    offerDeferTitle: 'Der Tag ist noch voll?',
    offerDeferYes: 'Ja, mach heute leichter',
    offerDeferYesA11y: 'Ja, heute leichter machen und ein paar Aufgaben verschieben',
    orderLine: 'Hier ist eine Reihenfolge, die fließen könnte. Nimm sie oder lass sie.',
    orderTitle: 'Eine sanfte Reihenfolge',
    phraseFinishKeep: 'was du schaffst, bleibt dir',
    phraseGentleForward: 'auch sanft geht es vorwärts',
    phraseOneThing: 'eine Sache, dann die nächste',
    phraseQuietDay: 'ein stiller Tag zählt auch',
    phraseRest: 'Ruhe gehört zur Arbeit',
    phraseSmallSteps: 'auch kleine Schritte tragen dich weiter',
    pin: 'Anpinnen',
    pinA11y: 'Diese Aufgabe als deine eine Sache für heute anpinnen',
    pinnedAffirm: 'Angepinnt. Deine eine Sache für heute.',
    rightNow: 'Jetzt gerade',
    allDayToolsA11y: 'Alle Werkzeuge des Tages',
    toolNow: 'jetzt',
    planNeedsTwo: '„Plan meinen Tag“ braucht zwei oder mehr Aufgaben.',
    focusNeedsOne: 'Fokus braucht erst mal etwas für heute.',
    lightenNeedsFull: '„Mach heute leichter“ ist für einen vollen Tag.',
    energyOverline: 'Energie',
    energyTitleA11y: 'Wie ist deine Energie heute?',
    energyPillLow: 'Wenig',
    energyPillNormal: 'Normal',
    energyPillHigh: 'Viel',
    planAskTitle: 'Bevor ich deinen Tag sortiere',
    planAskHint: 'Beantworte, was du magst. Den Rest lass einfach weg.',
    planAskEnergy: 'Wie ist deine Energie?',
    planAskDay: 'Was für ein Tag?',
    planAskSetting: 'Wo bist du?',
    planDayWork: 'Arbeitstag',
    planDayOff: 'Freier Tag',
    planSettingIn: 'Drinnen',
    planSettingOut: 'Unterwegs',
    planSettingEither: 'Beides',
    planAskGo: 'Sortier meinen Tag',
    planEditHint: 'Verschieb alles, wie du magst, oder nimm etwas raus. Nichts ändert sich, bis du den Plan übernimmst.',
    planMoveUpA11y: '{title} nach vorne schieben',
    planMoveDownA11y: '{title} nach hinten schieben',
    planDropA11y: '{title} aus diesem Plan nehmen',
    planEmpty: 'Nichts mehr im Plan. Das darf sein.',
    planning: 'Plane…',
    reentryBody: 'Egal, wie lange es her ist, die Vergangenheit ist in Ordnung. Nichts ist überfällig, nichts ist verloren. Hier ist nur heute, wenn du so weit bist.',
    reentryTitle: 'Willkommen zurück.',
    removeSelectedA11y: 'Ausgewählte entfernen',
    removeTaskLabel: '{title} entfernen',
    rowLabelBigSuffix: ', als viel markiert',
    rowLabelPinned: '{title}, angepinnt als deine eine Sache für heute',
    rowLabelReminderSuffix: ', Erinnerung um {time}',
    rowLabelRepeatingSuffix: ', wiederkehrend',
    saveStepsA11y: 'Diese Schritte speichern',
    seeToday: 'Heute ansehen',
    selectAll: 'Alle auswählen',
    selectAllA11y: 'Alle Aufgaben auswählen',
    selectHint: 'Tipp Aufgaben an, um sie auszuwählen',
    selectMore: 'Mehr auswählen',
    selectMoreA11y: 'Weitere Aufgaben auswählen, um sie gemeinsam zu bearbeiten',
    selectRowLabel: '{title} auswählen',
    selectedCount: '{count} ausgewählt',
    sequenceError: 'Gerade ließ sich keine Reihenfolge planen. Versuch es noch mal.',
    sliceHint: 'Teile diese eine Aufgabe in Schritte und hake sie nach und nach ab. Tipp sie auf Heute an, um einen Schritt weiterzugehen, wann immer du so weit bist.',
    sliceRowLabelComplete: '{title}, {done} von {total} erledigt, abgeschlossen',
    sliceRowLabelInProgress: '{title}, {done} von {total} erledigt, tippen für den nächsten Schritt, gedrückt halten zum Anpassen',
    sliceTitle: 'In Schritten zählen',
    slicesSetAffirm: 'In {count} Schritten. Tipp sie an, um einen Schritt weiterzugehen.',
    splitStepsA11y: 'Diese Aufgabe in Schritte teilen',
    spreadLine: 'Heute bleibt leichter. Hier könnte der Rest hin.',
    spreadTitle: 'Eine ruhigere Verteilung',
    stepBackLabel: '{title} einen Schritt zurücknehmen',
    steps: 'Schritte',
    stepsCount: '{count} Schritte',
    strategiseError: 'Heute ließ sich gerade nicht leichter machen. Versuch es noch mal.',
    subtitle: 'Nur heute. Der Rest kann warten.',
    syncPending: 'Auf diesem Gerät gespeichert. Es wird synchronisiert, sobald dein Konto erreichbar ist.',
    syncedFallbackAccount: 'deinem Konto',
    syncedTo: 'Synchronisiert mit {account}',
    thisWeekend: 'Dieses Wochenende',
    tinyAlreadyActive: 'Du hast dafür schon einen winzigen Schritt. Er ist da, wann immer du so weit bist.',
    tinyError: 'Das ließ sich gerade nicht winzig machen. Versuch es noch mal.',
    tinyMade: 'Winzig gemacht. Nur dieser eine Schritt.',
    tinyParentBackAffirm: 'Du hast angefangen, das ist der schwere Teil. {parentTitle} ist wieder da, wenn du so weit bist.',
    tinyShrinking: 'Wird winzig…',
    tinyStepEyebrow: 'Ein winziger Schritt Richtung · {parent}',
    tinyStepRowLabel: '{title}, ein winziger Schritt Richtung {parent}',
    undoAStep: 'Einen Schritt zurück',
    unmarkBigA11y: 'Die ausgewählten Aufgaben nicht mehr als viel markieren',
    unmarkBigOneA11y: 'Diese Aufgabe nicht mehr als viel markieren',
    unpin: 'Loslösen',
    unpinA11y: 'Diese Aufgabe loslösen',
    unpinnedAffirm: 'Losgelöst.',
    useOrder: 'Diese Reihenfolge übernehmen',
    useSpread: 'Diese Verteilung übernehmen',
    windDownSettle: 'Wenn heute noch laut ist, darfst du erst mal zur Ruhe kommen.',
    combineSub: 'legt ähnliche Aufgaben zusammen',
    combineAvailableAnnounce: 'Zusammenlegen möglich: zwei ähnliche Aufgaben.',
    removeCountA11y: 'Entfernt {count} Aufgaben',
    seriesContinues: 'die Reihe geht weiter',
    selectAllUnavailA11y: 'Alle auswählen nicht verfügbar, es ist schon alles ausgewählt',
  },
  triage: {
    summary: {
      forToday: '{count} für heute',
      forTomorrow: '{count} für morgen',
      line: 'Sortiert: {parts}.',
      toBreakDown: '{count} für kleine Schritte',
    },
  },
  updates: {
    nativeKept: 'Deine Listen bleiben genau so, wie sie sind.',
    nativeOld: 'Diese Version wird langsam alt.',
    notNow: 'Jetzt nicht',
    offer: 'Die neue kann alles lesen, was deine Person einstellt, Rhythmen inklusive.',
    openStore: 'Store öffnen',
    reload: 'Neu laden, um sie zu bekommen',
    upToDate: 'Aktuell',
    webKept: 'Was du gerade getippt hast, bleibt erhalten.',
    webReady: 'Eine neuere Version ist bereit.',
  },
  welcome: {
    appStoreBadgeA11y: 'DoubleDone im App Store laden',
    back: '‹ Zurück',
    backA11y: 'Einen Bildschirm zurück',
    beginA11y: 'Anfangen, DoubleDone öffnen',
    captureHeading: 'Was geht dir durch den Kopf?',
    captureInputA11y: 'Alles aus deinem Kopf, eine Sache pro Zeile',
    captureLead: 'Schreib einfach auf, was du gerade mit dir herumträgst. Eine Sache pro Zeile. Mach dir keinen Kopf um die Reihenfolge, das ist unser Job.',
    capturePlaceholder: 'Zahnarzt anrufen\nDana antworten\nGarage aufräumen\nKarte für Mama kaufen\nTabletten nehmen',
    capturePrivacyAi: '„Sortier für mich“ schickt diese Zeilen an Claude, um deinen Tag zu ordnen. „Ich sortiere selbst“ behält alles auf diesem Gerät.',
    capturePrivacyNoAi: 'Nur auf diesem Gerät. Nichts davon wird irgendwohin geschickt.',
    changeInSettings: 'In den Einstellungen ändern',
    changeInSettingsA11y: 'KI in den Einstellungen ändern',
    closingLine: 'Wenn du so weit bist, fang mit heute an.',
    footerFine: 'Eine installierbare App, die offline funktioniert. Heute ist überschaubar und machbar.',
    footerWho: 'Gemacht für ADHS, Autismus, Zwangsstörungen und alle, deren Liste sich je nach zu viel angefühlt hat.',
    handoffEthos: 'heute ist überschaubar und machbar',
    handoffFineAi: 'Von Haus aus bleibt alles auf deinem Gerät. Die KI-Funktionen schicken nur den Text, den du auswählst, an Claude, mehr nicht. Du willst es auch auf Handy und Laptop? Meld dich an, um zu synchronisieren, immer freiwillig.',
    handoffFineNoAi: 'Privat von Haus aus, nichts verlässt dein Gerät. Du willst es auch auf Handy und Laptop? Meld dich an, um zu synchronisieren, immer freiwillig.',
    handoffHeading: 'Das war’s. Keine Einrichtung.',
    handoffLead1: 'Es ist jetzt raus aus deinem Kopf, und alles ist hier. Morgen öffnet sich die App fertig vorbereitet, ohne dass du irgendetwas ordnen musst.',
    handoffLead2: 'Die Werkzeuge des Tages (planen, nur eine Sache, leichter machen, Feierabend) warten gesammelt unten, unter „Jetzt gerade“. Dein Kalender, deine Routinen und wiederkehrenden Aufgaben wohnen im Menü oben rechts.',
    heroHeadline: 'Heute ist überschaubar und machbar.',
    heroSub: 'Wenn sich eine To-do-Liste je nach zu viel angefühlt hat, darfst du sie hier ablegen. DoubleDone zeigt dir nur, was heute dran ist, und bewahrt still alles auf, was du schaffst.',
    howHeadline: 'Drei ruhige Schritte, vom Anfangen bis zum Feierabend.',
    howLabel: 'So läuft ein Tag',
    keepHeading: 'Was du schaffst, bleibt dir.',
    keepLead1: 'Alles, was du erledigst, landet in deinem Kalender, auch die Aufgabe, vor der du wochenlang Bammel hattest. Dein Gehirn kann dir nicht erzählen, du hättest nichts getan.',
    keepLead2: 'Jeden Abend machst du Feierabend. Er würdigt, was du getan hast, nie, was du nicht getan hast.',
    keepLead3: 'Hast du etwas getan, das nie auf deiner Liste stand? Trag es ruhig nach. Es zählt trotzdem.',
    keepScrapbook: 'Und einmal im Monat, kostenlos, kannst du eine geschaffte Woche in ein kleines Andenken-Bild verwandeln.',
    kicker: 'für Tage, an denen die Liste zu viel ist',
    playBadgeA11y: 'DoubleDone bei Google Play laden',
    reminderOffer: 'Magst du einen sanften Stupser am Tag, um wieder reinzuschauen? Du kannst ihn in den Einstellungen jederzeit ändern oder abstellen.',
    reminderOn: 'Eingerichtet. Ein leiser Stupser am Tag.',
    reminderNoThanks: 'Nein danke',
    widgetMention: 'Auf Android kannst du dir Heute auch auf den Startbildschirm holen, dann kommt es zu dir. Halte den Startbildschirm gedrückt, tippe auf Widgets und such nach DoubleDone.',
    lead1: 'Es zeigt dir nur, was heute dran ist, und bewahrt still alles auf, was du schaffst.',
    lead2: 'Nichts ist je überfällig. Es wartet einfach.',
    lead3: 'Gemacht für ADHS, Autismus, Zwangsstörungen und alle, deren Liste sich je nach zu viel angefühlt hat. Nichts hier wird dich je dafür beschämen, dass eine Aufgabe einfach da ist.',
    metaDescription: 'Eine ruhige To-do-App, die nie beschämt. Sie zeigt dir nur, was heute dran ist, und bewahrt still alles auf, was du schaffst. Gemacht für ADHS, Autismus und Zwangsstörungen. Nichts ist je überfällig.',
    metaOgImageAlt: 'DoubleDone · Heute, überschaubar und machbar',
    metaTitle: 'DoubleDone · eine ruhigere Art von To-do',
    mockTask1: 'Apotheke anrufen',
    mockTask2: 'Dana wegen Mietvertrag antworten',
    mockTask3: 'Steuerordner anfangen',
    mockTodayDate: 'Donnerstag, 27.',
    payoffBody: 'Alles, was du erledigst, sammelt sich in deinem Kalender, auch die Aufgabe, vor der du wochenlang Bammel hattest. Dein Gehirn kann dir nicht erzählen, du hättest nichts getan.',
    premiumChartWhat: 'ein Ziel wird zu ruhigen, geordneten Schritten.',
    premiumColourName: 'Deine Farbe',
    premiumColourWhat: 'sieben ruhige Farbthemen für die ganze App, du suchst dir deins aus.',
    premiumFine: 'A$5 im Monat, jederzeit kündbar. Es wartet in den Einstellungen, falls du mal neugierig wirst. Keine Werbung, nie.',
    premiumHeading: 'Und falls du mal ein bisschen mehr magst.',
    premiumLead: 'Alles, was du gerade gesehen hast, ist kostenlos, für immer. Premium ergänzt ein paar Extras, nie etwas, das du brauchst.',
    premiumPatternsName: 'Deine Muster',
    premiumPatternsWhat: 'sanfte Statistiken und ein warmer Wochenrückblick.',
    premiumPinName: 'Deine eine Sache anpinnen',
    premiumPinWhat: 'deine wichtigste Aufgabe bleibt ganz oben.',
    premiumQuietName: 'Stille',
    premiumQuietWhat: 'ein optionaler Look ohne Rahmen, in dem nichts schreit.',
    premiumPlanWhat: 'eine sanfte Reihenfolge für deine heutigen Aufgaben, mit einem Fingertipp.',
    premiumScanName: 'Liste scannen',
    premiumScanWhat: 'ein Foto deiner handgeschriebenen Liste, direkt als Aufgaben.',
    premiumScrapbookName: 'Ein wöchentliches Erinnerungsalbum',
    premiumScrapbookWhat: 'ein KI-Andenken an alles, was du in der Woche geschafft hast.',
    primaryLooksGood: 'Sieht gut aus, weiter',
    primaryOpenToday: 'Heute öffnen',
    primaryPutOnToday: 'Auf heute setzen',
    promiseBody: 'Und nichts hier wird dich je dafür beschämen, dass eine Aufgabe einfach da ist. Keine Streaks, keine Schuldgefühle, kein Rot.',
    revealAllTodayNote: 'Alles landet erst mal auf heute. Du kannst jederzeit etwas auf morgen oder später schieben.',
    revealBreakdownHint: 'Sieht groß aus, Schritte draus machen?',
    revealCombineHint: 'Ein paar Aufgaben, die zusammengehören? Halte eine gedrückt, tippe auf „Mehr auswählen“, wähle die anderen und leg sie zusammen.',
    revealCount: '{count} für heute.',
    revealHeading: 'Hier ist dein Heute, in machbarer Größe.',
    revealNoAiNote: 'Auf deinem Gerät sortiert, erst mal alles auf heute. Öffne später eine Aufgabe, um selbst Schritte draus zu machen.',
    revealRestWaiting: 'Der Rest wartet in Ruhe auf später.',
    safetyNetBreakWhat: 'in kleine Schritte, jeder nur ein paar Minuten.',
    safetyNetFocusWhat: 'der Rest verschwindet, nur eine Aufgabe bleibt im Blick.',
    safetyNetHeading: 'Wenn sich etwas zu groß anfühlt, bist du damit nicht allein.',
    safetyNetInscription: 'du darfst langsam machen',
    safetyNetLead: 'Gib DoubleDone eine Aufgabe, vor der du Bammel hast, und es hilft dir beim Anfangen:',
    safetyNetLightenWhat: 'ein zu voller Tag wird leichter, ein paar Aufgaben wandern auf spätere Tage.',
    safetyNetLowDayName: 'Sag, deine Energie ist niedrig',
    safetyNetLowDayWhat: 'ein Fingertipp oben in Heute, und was als genug zählt, wird sanft kleiner.',
    safetyNetNoAiBreakWhat: 'in kleine, machbare Schritte, die du selbst schreibst.',
    safetyNetTinyWhat: 'eine Zwei-Minuten-Version, nur zum Anfangen.',
    sharedHeading: "Eine Liste, die ihr beide führt.",
    sharedLead1: "Eine Liste, von zwei Menschen geführt. Für den Haushalt, den Einkauf oder die Pflege.",
    sharedLead2: "Was einen eigenen Tag hat, die Mülltonne am Dienstag, erscheint an dem Tag in euren beiden Heute. Wer abhakt, hakt für beide ab.",
    sharedLead3: "Alles andere wartet auf der Liste, niemand kann dir den Morgen schwerer machen. Dein Tag bleibt deiner, und er bleibt endlich.",
    sharedLead4: "Hier zählt nichts mit, und Erledigtes sagt nicht, wer es erledigt hat.",
    skipA11y: 'Die Einführung überspringen',
    sortMyself: 'Ich sortiere selbst',
    sortMyselfA11y: 'Selbst sortieren, alles bleibt auf diesem Gerät',
    step1Body: 'Tipp oder sprich alles ein, was gerade auf dir lastet. Die KI sortiert daraus ein machbares Heute und legt den Rest sanft beiseite.',
    step2Body: 'Hängst du an etwas Großem? Mach erste Schritte draus. Land unter? Mach den Tag mit einem Fingertipp leichter.',
    step2Title: 'Den Tag angehen',
    step3Body: 'Jeden Abend machst du Feierabend. Er würdigt, was du getan hast, nie, was du nicht getan hast. Morgen beginnt frisch.',
    step3Title: 'Sanft Feierabend machen',
    tagline: 'Eine ruhigere Art von To-do.',
    todayMockA11y: 'Der Heute-Bildschirm: zwei erledigte Aufgaben, Apotheke anrufen und Dana antworten, und eine offene, Steuerordner anfangen. Der Rest wartet in Ruhe auf später.',
    trustLine: 'Kostenlos. Kein Konto nötig. Funktioniert offline.',
  },
  whatsnew: {
    line1: 'Unsere Liste: eine Liste, die ihr zu zweit führt. Kostenlos, für immer.',
    line2: "Erledigt ist einfach erledigt. Nichts sagt, wer es war, also kann daraus kein Wettbewerb werden.",
    line3: 'Was einen Tag hat, erscheint bei euch beiden im Heute. Der Rest bleibt auf der Liste, damit dein Tag deiner bleibt.',
    line4: "Du findest sie im Menü.",
    title: 'Was ist neu',
  },
  widget: {
    allDoneForToday: 'Alles geschafft für heute.',
    closedForToday: 'Feierabend für heute.',
    more: '+{count} weitere',
    nothingForToday: 'Noch nichts für heute.',
    quickActionDumpSubtitle: 'Alles raus aus dem Kopf',
    quickActionDumpTitle: 'Kopf leeren',
    quickActionFocusSubtitle: 'Nur die nächste Sache',
  },
};
