"""Generate the translation-review spreadsheet for a native-speaker vibe-check.
Reads docs/i18n/review-data.json (the FULL catalog: every key, generated by the
i18n sweep) and writes docs/i18n/translations-review.xlsx: EN alongside Italiano /
Francais / Espanol, one row per string, with a green suggestion column the
reviewer edits. Rerun after any catalog change (regenerate review-data.json first).
  python scripts/gen-i18n-review.py
"""
import json
import os

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

HERE = os.path.dirname(__file__)
DATA = os.path.join(HERE, "..", "docs", "i18n", "review-data.json")
OUT = os.path.join(HERE, "..", "docs", "i18n", "translations-review.xlsx")

with open(DATA, encoding="utf-8") as f:
    rows = json.load(f)

HEADERS = ["Section", "Key", "English (do not edit)", "Italiano", "Français",
           "Español (current draft)", "Sugerencia / suggested fix (EDIT HERE)",
           "Note / context"]

wb = Workbook()
ws = wb.active
ws.title = "Translations"

intro = ("DoubleDone is a calm, gentle, never-pushy to-do app. This is the COMPLETE string set "
         "(every key in the app). For each row, read the English, then the Español draft. If anything "
         "sounds stiff, too formal, or just not how a real person would say it, put your fix in the green "
         "'Sugerencia' column (leave the original so we can compare). The voice is the warm, informal tú. "
         "Text in {curly braces} is a placeholder the app fills in: keep it exactly as written, but move it "
         "anywhere the sentence needs. A cell showing 'A  |  B' holds the singular and plural forms, fix "
         "either side of the bar. Italiano and Français are shown for cross-reference only.")
ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(HEADERS))
c = ws.cell(row=1, column=1, value=intro)
c.font = Font(italic=True, size=11)
c.alignment = Alignment(wrap_text=True, vertical="top")
ws.row_dimensions[1].height = 80

for col, h in enumerate(HEADERS, start=1):
    cell = ws.cell(row=2, column=col, value=h)
    cell.font = Font(bold=True, color="FFFFFF")
    cell.fill = PatternFill("solid", fgColor="4E8B5A" if col == 7 else "9B6A7D")
    cell.alignment = Alignment(wrap_text=True, vertical="center")
ws.freeze_panes = "A3"

EDIT_FILL = PatternFill("solid", fgColor="EAF6EA")
BAND_FILL = PatternFill("solid", fgColor="F5F0EA")
last_section = None
band = False
for i, r in enumerate(rows, start=3):
    if r["section"] != last_section:
        band = not band
        last_section = r["section"]
    values = [r["section"], r["id"], r["en"], r.get("it", ""), r.get("fr", ""), r.get("es", ""), "", r.get("note", "")]
    for col, val in enumerate(values, start=1):
        cell = ws.cell(row=i, column=col, value=val)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        if col == 3:
            cell.font = Font(color="555555")
        if col == 7:
            cell.fill = EDIT_FILL
        elif band:
            cell.fill = BAND_FILL

widths = [12, 30, 42, 34, 34, 40, 40, 30]
for col, w in enumerate(widths, start=1):
    ws.column_dimensions[get_column_letter(col)].width = w

wb.save(OUT)
print("wrote", os.path.abspath(OUT), f"({len(rows)} strings)")
